[[headers]]
  for = "/*"
  [headers.values]
    Origin = "https://schachtraining-lichess-discord.netlify.app"
    Access-Control-Allow-Origin = "https://schachtraining-lichess-discord.netlify.app"
    Access-Control-Allow-Headers = "access-control-allow-headers,content-type"